<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.15" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tanish.Application\Tanish.Application.csproj" />
    <ProjectReference Include="..\Tanish.Domain\Tanish.Domain.csproj" />
    <ProjectReference Include="..\Tanish.Infrostructure\Tanish.Infrastructure.csproj" />
  </ItemGroup>

</Project>
